[package]
name = "luna-rs-2"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
config = "0.14.0"
google-youtube3 = "5.0.5"
hyper = { version = "^0.14", features = ["client", "http1"] }
hyper-rustls = "0.27.3"
poise = "0.6.1"
reqwest = "^0.11"
songbird = "0.4.3"
symphonia = { version = "0.5.4", features = ["all"] }
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.2"
