services:
  luna-rs-dev:
    container_name: luna-rs-dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_PROFILE=debug
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    volumes:
      - ./Secrets.dev.toml:/app/Secrets.dev.toml:ro
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: rebuild
          path: ./Cargo.toml
